---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-secret
  namespace: default
spec:
  encryptedData:
    MONGO_URI: AgAoA6QGLn1VciktYjK6LNzdWOHrXnQMSp0ZcBC3m5yINAf1YGF48DOOkSQmiESPuP7ubgFhV7I6ynsrcVDdQHyDeX0PrxRb85Ery6Gf8jtZW8Kyo7yjPmJMODzc151TA+Ti4hu5suCb/MtpMMWa5BKGfKAa5xDDmAlRjvO9VMqzfrUiS5i0Ronj3DTLFJgUewfrqjzDEpCw0oXg3FpJmBbY+f1WWfzedK7y6VHC6wSUf8zM5jEeMF90lwM+Extt15ngTjZuhWFqIwCXrGvM53dhN3yjQ2Ai2SXiwk5xTGldtXp1QFvhd7Vf25T+khdad8Ax4peqcxQe4O3CCYZgFcw5CytwAk504J+9UdxclPivJuGBI2ETUW+luNVqqTk+Aa+EZqsN7ak6kUPCV8bk3AzK1m5fCpQ24N9xN75HWsDQYiG3s/R8dUv+2Aq0SYLWOQ/kWyh61Zqw/LnR1OMeHJU3WDgHBP9xkSLGDk857ikvW9Oz4uj/1N2ZTL6uvkxhylsHTVPDO2Hi6JeQGgmM2u0c2ohSsI6fIZPL2uPkgHbRHWcYCMJcfIFTiiNXlX9R6VFR81PcQDHGDF3rehYhsl0mEPoMm3+b76LYCbeof/JPhxZgDe3x3l1cKAquD1/y3z2Dwk53ru/ZD1LLN+W0wGTrJpvewh1I+dkvqxchWXXMJwfbvhenx9IQ2gZFG4QJRvXP+Q02bRUwT+ebgpdzIiiW6lBfP8nrPyltE7OHLTTX9N51yX8P25XaUchrTK3yayoRMIYjS2qytHIs0RY/rGNLF2oHOw3i
  template:
    metadata:
      name: db-secret
      namespace: default
    type: Opaque
